services:
  # Container Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: always

  # Container Nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Membaca sertifikat SSL langsung dari direktori OS Server Contabo (Read-Only)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - app
    restart: always

  # Container MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Container Certbot Dinonaktifkan (Karena SSL sudah di-generate langsung di OS Server)
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/www/certbot:/var/www/certbot

volumes:
  db_data: