server {
    listen 80;
    server_name dishub.khoirony.fun;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://app:9000; # Atau arahkan ke root laravel biasa dulu
        # Jika belum jalan, biarkan kosong atau arahkan ke root saja
        root /var/www/html/public;
        index index.php;
    }
}