server {
    listen 80;
    server_name bbmkapal-dishubjakarta.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect semua traffic HTTP ke HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name bbmkapal-dishubjakarta.com;

    # LIMIT UPLOAD DINAINKAN JADI 50MB
    client_max_body_size 50M;

    # Sertifikat SSL dari OS Server Host
    ssl_certificate /etc/letsencrypt/live/bbmkapal-dishubjakarta.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bbmkapal-dishubjakarta.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

# ==========================================
# REVERSE PROXY UNTUK DOMAIN STAGING
# ==========================================
server {
    listen 80;
    server_name stagingbbmkapal.khoirony.fun;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name stagingbbmkapal.khoirony.fun;

    # Nginx Production membaca sertifikat SSL milik domain Staging
    ssl_certificate /etc/letsencrypt/live/stagingbbmkapal.khoirony.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stagingbbmkapal.khoirony.fun/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Meneruskan traffic ke container Staging di port 8443
    location / {
        # Menggunakan IP VPS Contabo kamu
        proxy_pass http://217.217.252.239:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Limit upload 50MB
        client_max_body_size 50M;
    }
}