server {
    listen 80;
    server_name stagingbbmkapal.khoirony.fun;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect ke HTTPS dengan port 8443 (karena port 443 dipakai production)
    location / {
        return 301 https://$host:8443$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name stagingbbmkapal.khoirony.fun;

    client_max_body_size 50M;

    # SSL cert diarahkan ke folder Let's Encrypt untuk domain baru
    ssl_certificate /etc/letsencrypt/live/stagingbbmkapal.khoirony.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stagingbbmkapal.khoirony.fun/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app_staging:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
