name: Deploy to Contabo VPS

on:
  push:
    branches:
      - main # Trigger berjalan jika ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/bbm-kapal
            git pull origin main
            
            # 1. Variabel untuk Docker Compose (Wajib ada di paling atas pakai > untuk menimpa file)
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env

            # 2. Variabel untuk Laravel (Pakai >> untuk menambahkan baris)
            echo "APP_NAME=BBM-Kapal" >> .env
            echo "APP_ENV=production" >> .env
            echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            echo "APP_DEBUG=false" >> .env
            echo "APP_URL=http://${{ secrets.HOST }}:8080" >> .env
            
            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=db" >> .env
            echo "DB_PORT=3306" >> .env
            echo "DB_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "DB_USERNAME=root" >> .env
            echo "DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            
            docker-compose up -d --build
            docker image prune -f